apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd  # Argo CD only listen for application type to the argocd installed namespace(argo-cd in this case).So its constant.
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/maifujalam/k8s_aws/refs/heads/master/k8s/v1.31.3/manifests/ingress-nginx/values.yaml
    repoURL: https://public-helm-repository-20231023095000508500000001.s3.ap-south-1.amazonaws.com/
    targetRevision: 4.11.2-aws
  syncPolicy:
#    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
#      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
#      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
#      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
    - Validate=false
    - CreateNamespace=true
